project:
  type: website
  output-dir: docs

website:
  title: "FANR6750"
  site-url: "https://djklement.github.io/FANR6750/"

  navbar:
    left:
      - icon: house
        text: "" # no text to icon
        href: index.qmd

    right:

      - text: "Syllabus"
        icon: book
        href: syllabus.qmd

      - text: "Schedule"
        icon: calendar
        href: schedule.qmd

      - text: "Lectures"
        icon: file-pdf
        menu:

          - text: "Lecture 0: Course introduction"
            href: lectures/00_course_intro/00_course_intro.qmd

          - text: "Lecture 1: Introduction to statistics"
            href: lectures/01_intro_to_stats/01_intro_to_stats.qmd

          - text: "Lecture 2: Introduction to linear models"
            href: lectures/02_intro_to_lm/02_intro_to_lm.qmd

          - text: "Lecture 3: Principles of statistical inference"
            href: lectures/03_inference/03_inference.qmd

          - text: "Lecture 4: Linear models part 1: categorical predictor w/ 2 levels"
            href: lectures/04_ttest/04_ttest.qmd

          - text: "Lecture 5: Null hypothesis testing"
            href: lectures/05_nhst/05_nhst.qmd

          - text: "Lecture 6: Evaluation Assumptions"
            href: lectures/06_assumptions/06_assumptions.qmd

          - text: "Lecture 7: Principles of causal inference"
            href: lectures/07_causal_inference/07_causal_inference.qmd

          - text: "Lecture 8: Principles of experimental design"
            href: lectures/08_expdesign/08_expdesign.qmd

          - text: "Lecture 9: Linear models part 2: categorical predictor w/ > 2 levels"
            href: lectures/09_ANOVA/09_ANOVA.qmd

          - text: "Lecture 10: Multiple Comparisons"
            href: lectures/10_multcomp/10_multcomp.qmd

          - text: "Lecture 11: Power"
            href: lectures/11_power/11_power.qmd

          - text: "Lecture 12: Multiple Regression"
            href: lectures/12_multreg/12_multreg.qmd

          - text: "Lecture 13: Interactions"
            href: lectures/13_interactions/13_interactions.qmd

          - text: "Lecture 14:Causal Inference in Observational Studies"
            href: lectures/14_causal_inference_part2/14_causal_inference_part2.qmd

          #- text: "Lecture 15: Model Selection"
          #  href: lectures/15_model_selection.qmd

          #- text: "Lecture 16: Random Effects"
          #  href: lectures/16_random_eff.qmd

          #- text: "Lecture 17: Psuedoreplication Part 1: Nested Designs"
          #  href: lectures/17_nested.qmd

          #- text: "Lecture 18: Psuedoreplication Part 2: Repeated Measures"
          #  href: lectures/18_repeated_measures.qmd

          #- text: "Lecture 19: Logistic regression"
          #  href: lectures/19_logistic_regression.qmd

          #- text: "Lecture 20: Poisson regression"
          #  href: lectures/20_poisson_regression.qmd


      - text: "Labs"
        icon: display
        menu:

          - text: "Lab 1: Introduction to R"
            href: labs/lab01_intro_to_R.qmd
          #
          # - text: "Lab 2: Introduction to projects and RMarkdown"
          #   href: labs/lab02_Intro_project_and_Rmd.qmd
          #
          # - text: "Lab 3: Using R to explore sampling error"
          #   href: labs/lab03_inference.qmd
          #
          # - text: "Lab 4: t-tests"
          #   href: labs/lab04_t_tests.qmd
          #
          # - text: "Lab 5: ANOVA"
          #   href: labs/lab05_ANOVA.qmd
          #
          # - text: "Lab 6: Multiple Regression"
          #   href: labs/lab06_multiple_regression.qmd
          #
          # - text: "Lab 7: Interactions"
          #   href: labs/lab07_interactions.qmd
          #
          # - text: "Lab 8: Evaluating assumptions"
          #   href: labs/lab08_linear_model_assumptions.qmd
          #
          # - text: "Lab 9: Model selection"
          #   href: labs/lab09_model_selection.qmd
          #
          # - text: "Lab 10: Nested designs"
          #   href: labs/lab10_nested.qmd
          #
          # - text: "Lab 11: Split-plot designs"
          #   href: labs/lab11_split_plot.qmd
          #
          # - text: "Lab 12: Logistic regression"
          #   href: labs/lab13_glm_lr.qmd
          #
          # - text: "Lab 13: Poisson regression"
          #   href: labs/lab14_glm_pr.qmd
          #
          # - text: "Bonus lab: Repeated measures"
          #   href: labs/lab12_repeated_measures.qmd


      - text: "References"
        icon: pencil-square
        menu:

          - text: "Assignment instructions"
            href: references/homework.qmd

          - text: "Projects and directories"
            href: references/projects_and_directories.qmd

          - text: "R Markdown reference"
            href: references/RMarkdown.qmd

          - text: "Creating publication-quality graphics"
            href: references/graphics.qmd


format:
  html:
    theme: spacelab
    toc: true
    code-copy: true


