---
title: "Schedule (subject to change)"
subtitle: "FANR 6750: Experimental Methods in Forestry and Natural Resources Research"
author: "Fall 2025"
output: 
  rmarkdown::html_vignette:
    keep_md: yes
vignette: >
  %\VignetteIndexEntry{Schedule}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  collapse = TRUE, warning = FALSE, message = FALSE,
  comment = "#>"
)

source(here::here("R/MWF.R"))
```


```{r schedule, echo = FALSE}
library(kableExtra)

schedule <- data.frame(WK = c("1", "", "", 
                              "2", "", "", "",
                              "3", "", "", "", 
                              "4", "", "", "",
                              "5", "", "", "", 
                              "6", "", "", "", 
                              "7", "", "", "", 
                              "8", "", "", "",
                              "9", "", "", "", 
                              "10", "", "", "", 
                              "11", "", "", "", 
                              "12", "", "", "",
                              "13", "", "", "", 
                              "14", "", "", "", 
                              "15", "", "", "", 
                              "16", "", "", "", 
                              "17"),
                       Day = c("W", "F", "", rep(c("M", "W", "F", ""), 15), "M"),
                       Week = MWF(first.day = "2025/08/13", last.day = "2025/12/02"),
                       Lecture = c("Course introduction", "Introduction to statistics", "", #1
      "Introduction to linear models",  "Introduction to linear models", "Principles of statistical inference", "",#2
      "Principles of statistical inference", "Principles of experimental design", "Principles of experimental design", "", #3
      "Labor Day", "Linear models for simple categorical predictors (aka t-test)", "Linear models for simple categorical predictors (aka t-test)", "", # 4
       "Null hypothesis testing", "Null hypothesis testing", "Troubleshooting R workshop", "", #5
       "Power", "Linear models for categorical predictor w/ >2 levels (aka ANOVA)", "Linear models for categorical predictor w/ >2 levels (aka ANOVA)", "", #6
      "Multiple comparisons", "Special topic: p-hacking", "**Exam 1**",  "", #7
       "Multiple regression","Multiple regression",  "Interactions",  "", #8 
             "Interactions", "Evaluating assumptions", "Model selection",  "", #9
      "Random effects", "Nested designs", "Split-plot designs", "", # 10
          "Split-plot designs", "Special topic: AI", "**Exam 2**", "", #11
       "Repeated measures", "Repeated measures", "Fall break", "",
         "Repeated measures", "Buffer", "Generalized linear models", "", #13 
      "GLM: Logistic regression", "GLM: Logistic regression", "GLM: Poisson regression", "", #14
          "GLM: Poisson regression", "GLM: Zero-inflated data", "GLM: Zero-inflated data", "", #15
          "Special topic: Causal inference", "Thanksgiving break", "", "", #16
             "**Exam 3**"), 
      Reading = c("[Syllabus](https://rushinglab.github.io/FANR6750/articles/syllabus.html)", "[Quinn chp. 1](https://www2.ib.unicamp.br/profs/fsantos/apostilas/Quinn%20&%20Keough.pdf#page=21.08)", "",
                               "[Fieberg chp. 1.2-1.4](https://statistics4ecologists-v3.netlify.app/01-linearregression)", "", "[Feiberg chp. 1.6-1.8](https://statistics4ecologists-v3.netlify.app/01-linearregression#sec-sampdist)", "",
                               "", "[Quinn chp. 7.1-7.2](https://www2.ib.unicamp.br/profs/fsantos/apostilas/Quinn%20&%20Keough.pdf#page=175.08)", "", "",
                               "", "[Fieberg chp. 3.6](https://statistics4ecologists-v3.netlify.app/03-multipleregression#categorical-predictors)", "", "",
                               "[Fieberg chp. 1.10](https://statistics4ecologists-v3.netlify.app/01-linearregression#hypothesis-tests-and-p-values)
", "", "", "",
                                "[Quinn chp. 7.3](https://www2.ib.unicamp.br/profs/fsantos/apostilas/Quinn%20&%20Keough.pdf#page=175.08)", "[Fieberg chp. 3.7](https://statistics4ecologists-v3.netlify.app/03-multipleregression#sec-ancova)", "", "",
                               "[Fieberg chp. 3.9,](https://statistics4ecologists-v3.netlify.app/03-multipleregression#pairwise-comparisons) [3.12](https://statistics4ecologists-v3.netlify.app/03-multipleregression#sec-contrasts)", "[Fraser et al. 2018](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0200303)", "", "",
                               "[Fieberg chp. 3.2-3.5](https://statistics4ecologists-v3.netlify.app/03-multipleregression#introduction-to-multiple-regression)", "", "[Fieberg chp. 3.8](https://statistics4ecologists-v3.netlify.app/03-multipleregression#models-with-interactions)", "",
                               "", "", "[Tredennick et al. 2021](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecy.3336)", "",
                               "", "", "", "",
                               "", "[Bergstrom & West 2025](https://thebullshitmachines.com/table-of-contents/index.html)", "", "",
                               "", "",  "", "",
                               "", "", "", "",
                               "", "", "", "",
                               "", "", "", "",
                               "[Fieberg chp. 7](https://statistics4ecologists-v3.netlify.app/07-causalnetworks)", "", "", "",
                               ""),
                       Lab = c("", "", "",
                               "Introduction to R", "", "", "",
                               "Introduction to RMarkdown", "", "", "",
                               "No lab", "", "", "",
                               "Sampling error*", "", "", "",
                               "t-tests*", "", "", "",
                               "ANOVA", "", "", "",
                               "Multiple regression*", "", "", "",
                               "Interactions*", "", "", "",
                               "Evaluating assumptions*", "", "", "",
                               "Nested design", "", "", "",
                               "Split-plot designs*", "", "", "",
                               "Repeated measures*", "", "", "",
                               "Model selection*", "", "", "",
                               "GLMs*", "", "", "",
                               "No lab", "", "", "",
                               "No lab"))

schedule %>%
  kable("html", col.names = c("Week", "", "Date", "Lecture topic", "Reading", "Lab Topic"), align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = TRUE)

```

\* = Graded assignment

